# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6550cd53-0585-4fe9-8d29-2ca562df74bd";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."nixcrypt".device = "/dev/disk/by-uuid/03dbe62a-9856-49af-9bca-07687e1075b3";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6550cd53-0585-4fe9-8d29-2ca562df74bd";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6550cd53-0585-4fe9-8d29-2ca562df74bd";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA63-B2BC";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/var/swap"; } ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
