# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/66b4278a-5b8a-4aca-ab61-a62908e11bb5";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."nixcrypt".device =
    "/dev/disk/by-uuid/79c73be1-fbb1-49aa-969b-86232eadc1a2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EE1D-4F00";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/var/swap";
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
